/* SQL DEVELOPER에서는 CONN 명령이 안먹는다.
그래서 CMD창에서 SQLPLUS로 접속하여 SYSTEM계정으로 
권한을 줘야 한다*/

--ex15_1
--SCOTT계정으로 실행하면 권한이 없다고 나온다.
CREATE USER ORCLSTUDY 
IDENTIFIED BY ORACLE;

--ex15_2
--SYSTEM으로 실행(SESSION 권한이 없다고 나온다)
CREATE USER ORCLSTUDY
IDENTIFIED BY ORACLE;

SHOW USER;

--ex15_3
--CREATE SESSION권한(접속) 주기, (SYSTEM계정에서 줘야 한다.)
GRANT CREATE SESSION TO ORCLSTUDY;

CONN ORCLSTUDY/ORCL; --이젠 접속 됨

--ex15_4
--비번 변경
ALTER USER ORCLSTUDY IDENTIFIED BY ORCL;

--ex15_5
--USER 삭제
DROP USER ORCLSTUDY;

--ex15_6
DROP USER ORCLSTUDY CASCADE;


--ex15_7
CREATE USER ORCLSTUDY
IDENTIFIED BY ORACLE;

--ex15_8
--권한 RESOURCE, CREATE SESSION, CREATE TABLE (ORCLSTUDY 유저에게 권한을 준다.)
GRANT RESOURCE, CREATE SESSION, CREATE TABLE TO ORCLSTUDY;

CONN ORCLSTUDY/ORACLE;

SHOW USER;

--ex15_9
CONN SCOTT/tiger;

CREATE TABLE TEMP (
COL1 VARCHAR(20),
COL2 VARCHAR(20)
);

--ex15_10
--객체 권한을 다른 USER에게 부여한다(관리자가 아닌 일반 USER도 가능하다)
--SCOTT가 만든 TEMP 테이블에 INSERT, SELECT 사용 권한을 부여한다.
GRANT SELECT, INSERT ON TEMP TO ORCLSTUDY;

--ex15_11
CONN ORCLSTUDY/ORACLE;

SELECT * FROM SCOTT.TEMP; --SCOTT의 테이블이므로 SCOTT.테이블명

INSERT INTO SCOTT.TEMP VALUES('TEXT', 'FROM ORCLSTUDY');

SELECT * FROM SCOTT.TEMP;

--ex15_12
CONN SCOTT/tiger;

REVOKE SELECT, INSERT ON TEMP FROM ORCLSTUDY; 
/* 권한 회수, 권한은 부여한 사람이 회수 할 수 있고,
부여받은 사람은 회수하지 못한다. */

--ex15_13
CONN ORCLSTUDY/ORACLE;

SELECT * FROM SCOTT.TEMP; --권한이 없어서 조회 X

--ex15_14
CONN SYSTEM/ORACLE; --ROLL은 관리자가 만든다.

CREATE ROLE ROLESTUDY; --ROLL객체 생성

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM TO ROLESTUDY;
--ROLL객체에 ROLL이나 권한을 부여한다.

--ex15_15
--USER에게 생성한 ROLL을 부여한다 
GRANT ROLESTUDY TO ORCLSTUDY;

--ex15_16
CONN ORCLSTUDY/ORACLE;

SELECT * FROM USER_SYS_PRIVS;

SELECT * FROM USER_ROLL_PRIVS;

