--ex10_1
--테이블 구조 및 데이터까지 복사해서 새 테이블을 생성한다.
CREATE TABLE DEPT_TEMP1
AS SELECT * FROM DEPT;

--ex10_2
SELECT * FROM DEPT_TEMP;

--ex10_3
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (50, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_TEMP;

--ex10_4
--지정할 컬럼을 생략
--값 입력은 테이블에 정의된 컬럼 순서대로 모든 값을 입력해야함(비 권고)
INSERT INTO DEPT_TEMP
VALUES (60, 'NETWORK', 'BUSAN');

SELECT * FROM DEPT_TEMP;

--ex10_5
--명시적으로 NULL값 입력
INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC)
VALUES(70, 'WEB', NULL);

SELECT * FROM DEPT_TEMP;

--ex10_6
--문자열이나 DATE값일시 빈 값만 ''으로 입력
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES(80, 'MOBILE', NULL);

SELECT  * FROM DEPT_TEMP;

--ex10_7
--컬럼을 지정하지 않는 묵시적인 방법 (비권고)
INSERT INTO DEPT_TEMP (DEPTNO, LOC)
VALUES(90, 'INCHEON');

SELECT * FROM DEPT_TEMP;

--ex10_8
CREATE TABLE EMP_TEMP
AS SELECT * FROM EMP WHERE 1 <> 1;

SELECT * FROM EMP_TEMP;

--ex10_9
INSERT INTO EMP_TEMP (EMPNO, ENAME, 
JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (9999, '홍길동', 'PRESIDENT', NULL, '2001/01/01', 5000, 1000, 10);

SELECT * FROM EMP_TEMP;

--ex10_10
INSERT INTO EMP_TEMP (EMPNO, ENAME, 
JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (9999, '홍길동', 'PRESIDENT', NULL, '2001-01-05', 5000, 1000, 10);

SELECT * FROM EMP_TEMP;

--ex10_EX
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (9999, '홍길동', 'PRESIDENT', NULL, '1994-01-05', 5000, 1000, 10);

SELECT * FROM EMP_TEMP;

--ex10_11
--YYYY/MM/DD나 YYYY-MM-DD가 아닌 형식으로 출력시 에러
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(9999, '김정은', 'PRESIDENT', NULL, '07-01-2023', 5000, 1000, 10);

SELECT * FROM EMP_TEMP;

--ex10_12
/* 오라클의 날짜 표시 기본 형식이 아닌 문자열을 사용시 
TO_DATE(문자열, 사용포맷)을 이용 결과는 오라클 
기본 형식으로 표시 된다(YY/MM/DD) */
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (2111, '이순신', 'MANAGER', 9999, 
TO_DATE('07/01/2001', 'DD/MM/YYYY'), 4000, NULL, 20);

SELECT  * FROM EMP_TEMP;

--ex10_13
--SYSDATE함수는 현재 시각을 반환
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(3111, '심청이', 'MANAGER', 9999, SYSDATE, 4000, NULL, 30);

SELECT * FROM EMP_TEMP;

--ex10_14
/* 기존 테이블의 데이터를 INSERT를 할때 VALUES가 아닌 
SELECT 서브쿼리 사용 */
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
FROM EMP E, SALGRADE S -- 두 테이블을 사용
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL --비등가 조인
AND S.GRADE = 1;

SELECT * FROM EMP_TEMP;

--ex10_15
CREATE TABLE DEPT_TEMP2
AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP2;

--ex10_16 --UPDATE
--모든 행의 LOC컬럼을 SEOUL로 변경 (WHERE 조건절이 없어서 모두 변경됨)
UPDATE DEPT_TEMP2
SET LOC = 'SEOUL';

SELECT * FROM DEPT_TEMP2;

--ex10_17
--잘못된 조작문을 취소시킬때 주로 사용함 (단, COMMIT이전에 실행해야 정상작동함)
ROLLBACK;

--ex10_18
--WHWERE절로 UPDATE행 제한
UPDATE DEPT_TEMP2
SET DNAME = 'DATABASE', LOC = 'SEOUL'
WHERE DEPTNO = 40;

SELECT * FROM DEPT_TEMP2;

--ex10_19
--두개의 컬럼 값을 서브쿼리로 여러 행을 수정한다.
UPDATE DEPT_TEMP2
SET (DNAME, LOC) =  --복수개의 컬럼을 ( ) 에 넣어 처리
(SELECT DNAME, LOC FROM DEPT WHERE DEPTNO = 40)
WHERE DEPTNO = 40;

SELECT * FROM DEPT_TEMP2;

--ex10_20
UPDATE DEPT_TEMP2
SET DNAME = --각각의 컬럼값을 서브쿼리로 처리
(SELECT DNAME FROM DEPT WHERE DEPTNO = 40),
LOC = --각각의 컬럼값을 서브쿼리로 처리
(SELECT LOC FROM DEPT WHERE DEPTNO = 40)
WHERE DEPTNO = 40;

SELECT * FROM DEPT_TEMP2;

--ex10_21
UPDATE DEPT_TEMP2
SET LOC = 'SEOUL'
WHERE DEPTNO = 
(SELECT DEPTNO --WHERE절의 서브쿼리
FROM DEPT_TEMP2
WHERE DNAME = 'OPERATIONS');

SELECT * FROM DEPT_TEMP2;

--ex10_22
/* 
CREATE DDL명령을 사용하면 COMMIT가 일어나서 
앞에서 실행했던 조작문들이 모두 영구 보존된다 
(자동으로 COMMIT 된다는 의미이다.)
*/
CREATE TABLE EMP_TEMP2 
AS SELECT * FROM EMP;

SELECT * FROM EMP_TEMP2;

--ex10_23 - DELETE
--WHERE조건에 맞는 행을 삭제한다.
DELETE FROM EMP_TEMP2
WHERE JOB = 'MANAGER';

ROLLBACK;

SELECT * FROM EMP_TEMP2;

--ex10_24
--조건에 서브 쿼리를 사용했다.
DELETE FROM EMP_TEMP2
WHERE EMPNO IN
            (SELECT E.EMPNO 
            FROM EMP_TEMP2 E, SALGRADE S
            WHERE E.SAL 
            BETWEEN S.LOSAL AND S.HISAL 
            AND S.GRADE = 3 AND DEPTNO = 30);

ROLLBACK;

SELECT * FROM EMP_TEMP2;

--ex10_25
DELETE FROM EMP_TEMP2;

ROLLBACK;

SELECT * FROM EMP_TEMP2;
