--ex11_1
CREATE TABLE DEPT_TCL
AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TCL;

--ex11_2
INSERT INTO DEPT_TCL VALUES(50, 'DATABASE', 'SEOUL');

UPDATE DEPT_TCL
SET LOC =  'BUSAN'
WHERE DEPTNO = 40;

DELETE FROM DEPT_TCL
WHERE DNAME = 'RESEARCH';

SELECT * FROM DEPT_TCL;

--ex11_3
--여기서 ROLLBACK을 실행시 지금까지의 TRANSACTION은 종료된다.
ROLLBACK;

SELECT * FROM DEPT_TCL;

--ex11_4
INSERT INTO DEPT_TCL VALUES (50, 'NETWORK', 'SEOUL');

UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 20;

DELETE DEPT_TCL WHERE DEPTNO = 50;

SELECT * FROM DEPT_TCL;

--ex11_5 - COMMIT : 영구적으로 반영 시키기
COMMIT; --현재의 TRANSACTION상태의 DML

--ex11_6
SELECT * FROM DEPT_TCL; --SQL DEVELOPER

SELECT * FROM DEPT_TCL; --SQL PLUS

--ex11_7
DELETE FROM DEPT_TCL WHERE DEPTNO = 50;

SELECT * FROM DEPT_TCL; --SQL DEVELOPER

SELECT * FROM DEPT_TCL; --SQL PLUS

--ex11_8
COMMIT; --트랜잭션 완료(영구보존) 이후에는 다른 세션에서도 조회 및 작업 가능

SELECT * FROM DEPT_TCL; --SQL DEVELOPER

SELECT * FROM DEPT_TCL; --SQL PLUS

--ex11-9
SELECT * FROM DEPT_TCL; --디벨로퍼
SELECT * FROM DEPT_TCL; --SQL PLUS

--ex11-10
UPDATE DEPT_TCL SET LOC='SEOUL'
WHERE DEPTNO = 30; --디벨로퍼

SELECT * FROM DEPT_TCL; --디벨로퍼
SELECT * FROM DEPT_TCL; --SQL PLUS (아직 반영되지 않은 자료)

--ex11-11
/* 타 세션에서 작업이 트랜잭션 처리가 안되어 LOCK상태이므로
작업을 처리하지 못하는 상태(작업 중단)로 대기한다. */
UPDATE DEPT_TCL
SET DNAME='DATABASE' --SQL PLUS에서 작업 미반영
WHERE DEPTNO = 30; --SQL PLUS

--ex11-12
COMMIT; --디벨로퍼

--ex11-13
SELECT * FROM DEPT_TCL; --디벨로퍼에선 SQLPLUS의 UPDATE가 안보인다.
SELECT * FROM DEPT_TCL; --SQL PLUS

--ex11-14
COMMIT; --SQL PLUS

--ex11-15
SELECT * FROM DEPT_TCL; --디벨로퍼